[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production]
    publish = "output/"
    command = "make publish"
    environment = { NODE_VERSION = "14.15.3" }